language: node_js

node_js:
  - "stable"

after_success:
  - npm run deploy
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $PORTFOLIO_ACCESS_TOKEN
#   keep_history: true
#   on:
#     branch: master
